"""
Order + OrderItem models.

`daily_order_id` stores the human-friendly, acoustic-proof identifier
("A1", "A2", ...) that staff can call out loud without ambiguity. It is
generated by `services/order_id_service.py` using the DailyCounter table
and reset every night by the scheduler.
"""
import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.database.base import Base, TimestampMixin, UUIDPKMixin
from src.models.enums import OrderStatus, OrderType


class Order(Base, TimestampMixin, UUIDPKMixin):
    __tablename__ = "orders"
    __table_args__ = (
        # Prevent two orders sharing the same daily_order_id on the same day
        Index("ix_orders_daily_id_date", "daily_order_id", "order_date", unique=True),
        Index("ix_orders_session_uuid_status", "session_uuid", "status"),
        CheckConstraint("total_amount >= 0", name="ck_orders_total_amount_non_negative"),
    )

    daily_order_id: Mapped[str] = mapped_column(String(10), nullable=False)
    # Timezone-aware to match the timezone-aware datetimes services store here.
    order_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    session_uuid: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("sessions.session_uuid", ondelete="SET NULL"), nullable=True
    )
    table_number: Mapped[str | None] = mapped_column(String(20), nullable=True)

    order_type: Mapped[OrderType] = mapped_column(
        Enum(OrderType, name="order_type_enum"), nullable=False
    )
    status: Mapped[OrderStatus] = mapped_column(
        Enum(OrderStatus, name="order_status_enum"),
        default=OrderStatus.PENDING_PAYMENT,
        nullable=False,
        index=True,
    )

    total_amount: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    eta_minutes: Mapped[int] = mapped_column(Integer, nullable=True)
    special_instructions: Mapped[str | None] = mapped_column(Text, nullable=True)

    session: Mapped["Session"] = relationship(back_populates="orders")
    items: Mapped[list["OrderItem"]] = relationship(
        back_populates="order", cascade="all, delete-orphan"
    )
    payment: Mapped["Payment"] = relationship(
        back_populates="order", uselist=False, cascade="all, delete-orphan"
    )
    kitchen_entry: Mapped["KitchenQueue"] = relationship(
        back_populates="order", uselist=False, cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Order {self.daily_order_id} status={self.status}>"


class OrderItem(Base, UUIDPKMixin):
    __tablename__ = "order_items"

    order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("orders.id", ondelete="CASCADE"), nullable=False
    )
    menu_item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("menu_items.id", ondelete="RESTRICT"), nullable=False
    )
    quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    unit_price: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    subtotal: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    notes: Mapped[str | None] = mapped_column(String(255), nullable=True)

    order: Mapped["Order"] = relationship(back_populates="items")
    menu_item: Mapped["MenuItem"] = relationship(back_populates="order_items")

    @property
    def name(self) -> str | None:
        return self.menu_item.name if self.menu_item else None

    @property
    def item_name(self) -> str | None:
        return self.menu_item.name if self.menu_item else None

    __table_args__ = (
        CheckConstraint("quantity > 0", name="ck_order_items_quantity_positive"),
    )
